hey-url-challenge-code-dotnet/ViewModels/ErrorViewModel.cs
namespace HeyUrlChallengeCodeDotnet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

hey-url-challenge-code-dotnet/ViewModels/HomeViewModel.cs
using System.Collections.Generic;
using hey_url_challenge_code_dotnet.Models;

namespace hey_url_challenge_code_dotnet.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Url> Urls { get; set; }
        public Url NewUrl { get; set; }
        public int urlPage { get; set; }
        public bool maxPage { get; set; }
        public string absolutePath { get; set; }
    }
}

hey-url-challenge-code-dotnet/ViewModels/ShowViewModel.cs
using System.Collections.Generic;
using hey_url_challenge_code_dotnet.Models;

namespace hey_url_challenge_code_dotnet.ViewModels
{
    public class ShowViewModel
    {
        public Url Url { get; set; }
        public Dictionary<string, int> DailyClicks { get; set; }
        public Dictionary<string, int> BrowseClicks { get; set; }
        public Dictionary<string, int> PlatformClicks { get; set; }
    }
}

hey-url-challenge-code-dotnet/Controllers/UrlsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using hey_url_challenge_code_dotnet.Bll.Interface;
using hey_url_challenge_code_dotnet.Models;
using hey_url_challenge_code_dotnet.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Shyjus.BrowserDetection;
using static hey_url_challenge_code_dotnet.Bll.UrlBLL;
using PagedList;

namespace HeyUrlChallengeCodeDotnet.Controllers
{
    [Route("/")]
    public class UrlsController : Controller
    {
        private readonly ILogger<UrlsController> _logger;
        private static readonly Random getrandom = new Random();
        private readonly IBrowserDetector browserDetector;
        private readonly IUrlBLL _urlBLL;

        public UrlsController(IUrlBLL urlBLL, ILogger<UrlsController> logger, IBrowserDetector browserDetector)
        {
            _urlBLL = urlBLL;
            this.browserDetector = browserDetector;
            _logger = logger;
        }

        public async Task<IActionResult> Index(int page = 0)
        {
            var model = new HomeViewModel();

            var lstUrl = await _urlBLL.GetUrlList(page);

            List<Url> lstUrlsModel = new List<Url>();

            lstUrl.Item1.data.ForEach(x =>
            {
                lstUrlsModel.Add(new hey_url_challenge_code_dotnet.Models.Url()
                {
                    ShortUrl = x.attributes.shortUrl,
                    Count = _urlBLL.GetUrlClicks(int.Parse(x.id)).Result.data.Count(),
                    OriginalUrl = x.attributes.originalUrl,
                    CreatedAt = x.attributes.createdAt,
                    Id = int.Parse(x.id)
                });

            });
            model.Urls = lstUrlsModel;
            model.urlPage = page == 0 ? 1 : page;
            model.absolutePath = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}";
            if (lstUrl.Item2)
            {
                model.maxPage = true;
            }



            model.NewUrl = new();
            return View(model);
        }

        [Route("/{url}")]
        public async Task<IActionResult> Visit(string url)
        {
            var website = await _urlBLL.GetUrlByShortUrl(url);
            if (website.data.Count == 0)
                return NotFound();
            else
            {
                var idUrl = int.Parse(_urlBLL.GetUrlByShortUrl(RouteData.Values["url"].ToString()).Result.data[0].id);
                var success = await _urlBLL.CreateClick(idUrl, this.browserDetector.Browser.OS, this.browserDetector.Browser.Name);
                return Redirect(website.data.First().attributes.originalUrl);
            }
                
        }

        [Route("urls/{url}")]
        public async Task<IActionResult> Show(int idUrl, bool saveClick = true)
        {
            if (saveClick)
            {
                if (idUrl == 0)
                {
                    idUrl =  int.Parse(_urlBLL.GetUrlByShortUrl(RouteData.Values["url"].ToString()).Result.data[0].id);
                }
                var success = await _urlBLL.CreateClick(idUrl, this.browserDetector.Browser.OS, this.browserDetector.Browser.Name);
            }

            var model = await _urlBLL.GetUrl(idUrl);
            var clicks = await _urlBLL.GetUrlClicks(idUrl);
            var clicksModel = clicks.data.Where(x => x.type == "clicks");
            var clicksDay = clicksModel.Where(x => x.attributes.createdAt.Date == DateTime.Now.Date);
            var clicksBrowse = clicksModel.Select(x => x.attributes.browser).Distinct();
            var browsers = clicksModel.GroupBy(x => x.attributes.browser)
            .Where(x => x.Count() > 0)
            .Select(x => new { Value = x.Key, Count = x.Count() })
              .ToDictionary(x => x.Value, x => x.Count);
            var platform = clicksModel.GroupBy(x => x.attributes.platform)
             .Where(x => x.Count() > 0)
             .Select(x => new { Value = x.Key, Count = x.Count() })
             .ToDictionary(x => x.Value, x => x.Count);
            var daily = clicksModel.Where(x => DateTime.Now.Month == x.attributes.createdAt.Month).GroupBy(x => x.attributes.createdAt.Date)
                .Where(x => x.Count() > 0)
                .Select(x => new { Value = x.Key.Day.ToString(), Count = x.Count() })
                .ToDictionary(x => x.Value, x => x.Count);



            ShowViewModel modelReturn = new ShowViewModel()
            {
                Url = new Url { OriginalUrl = model.data.attributes.originalUrl, CreatedAt = model.data.attributes.createdAt, Id = int.Parse(model.data.id), ShortUrl = model.data.attributes.shortUrl },
                DailyClicks = daily,
                BrowseClicks = browsers,
                PlatformClicks = platform
            };
            return View(modelReturn);
        }

        [HttpPost]
        public async Task<IActionResult> Create(HomeViewModel url)
        {
            Url newUrl = new Url();

            Uri uriResult;
            bool result = Uri.TryCreate(url.NewUrl.OriginalUrl, UriKind.Absolute, out uriResult)
                && (uriResult.Scheme == Uri.UriSchemeHttp || uriResult.Scheme == Uri.UriSchemeHttps);

            if (result)
            {
                newUrl = await _urlBLL.CreateUrl(url.NewUrl);
                url.NewUrl = newUrl;
                return RedirectToAction("Show", new { idUrl = url.NewUrl.Id, saveClick = false });
            }
            else
            {
                TempData["Notice"] = "Invalid Url";
                return RedirectToAction("Index");
            }


        }
    }
}

hey-url-challenge-code-dotnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/materialize/css/materialize.min.css" />
    <script src="~/lib/materialize/js/materialize.min.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>
<body>
    <nav>
        <div class="nav-wrapper">
            <a class="brand-logo" asp-area="" asp-controller="Urls" asp-action="Index">HeyURL!</a>
        </div>
    </nav>
    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>

hey-url-challenge-code-dotnet/Views/Urls/Index.cshtml
@model hey_url_challenge_code_dotnet.ViewModels.HomeViewModel

@{
	ViewData["Title"] = "Home Page";
	var pageDisabled = Model.urlPage == 1;
	var maxPage = Model.maxPage;
	
}

@if (TempData["Notice"] is not null)
{
	<div class="card-panel notice deep-orange">@TempData["Notice"]</div>
}

<div class="row">
	<div class="col m12">
		<form asp-action="Create">
			<div class="card">
				<div class="card-content">
					<div class="row">
						<div class="col m8 offset-m2 center-align">
							<span class="card-title">Create a new short URL</span>
						</div>
					</div>
					<div class="row">
						<div class="col m6 offset-m2">
							<input type="text" asp-for="NewUrl.OriginalUrl" class="validate form-control" placeholder="Your original URL here" />
						</div>
						<div class="col m2">
							<button type="submit" class="btn">Shorten URL</button>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
<table class="table highlight">
	<thead>
		<tr>
			<th scope="col">Short URL</th>
			<th scope="col">Original URL</th>
			<th scope="col">Created</th>
			<th scope="col">Clicks Count</th>
			<th scope="col">Stats</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var url in Model.Urls)
		{
			<tr>
				<th scope="row">
					<a href="@(Model.absolutePath)/@(url.ShortUrl)">@url.ShortUrl</a>
				</th>
				<td>
					<a href="@url.OriginalUrl">@(url.OriginalUrl)</a>
				</td>
				<td>
					<!-- Please match the same format -->Feb 24, 2021
			</td>
				<td>@url.Count</td>
				<td>
					<a href=@string.Format("/urls/{0}?idUrl={1}", url.ShortUrl,url.Id)>
						<svg class="octicon octicon-graph" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">
							<path fill-rule="evenodd" d="M16 14v1H0V0h1v14h15zM5 13H3V8h2v5zm4 0H7V3h2v10zm4 0h-2V6h2v7z"></path>
						</svg>
					</a>
				</td>
			</tr>
		}
	</tbody>
</table>

<ul class="pagination justify-content-center">
	@if (!pageDisabled)
	{
		<li class="page-item">
			@Html.ActionLink("Previous","Index",new { page = Model.urlPage - 1 })
		</li>
	}
	@if (maxPage)
	{
		<li class="page-item ">
			@Html.ActionLink("Next","Index", new { page = Model.urlPage + 1 })
		</li>
	}

</ul>

hey-url-challenge-code-dotnet/Views/Urls/Show.cshtml
@model hey_url_challenge_code_dotnet.ViewModels.ShowViewModel

@{
	ViewBag.Title = "Show";
	Layout = "_Layout";
}

<div class="row">
	<div class="col s12">
		<ul class="card-panel collection with-header">
			<li class="collection-header">
				<h4>
					Stats for @Html.ActionLink(Model.Url.ShortUrl,"Show", new {idUrl = Model.Url.Id})
				</h4>
			</li>
			<li class="collection-item">@Model.Url.CreatedAt.ToString("dddd, dd MMMM yyyy")</li>
			<li class="collection-item">
				Original URL: @Model.Url.OriginalUrl
			</li>
		</ul>
	</div>
</div>
@if (Model.DailyClicks.Count() > 0)
{
	<div class="row">
		<div class="col s12">
			<div class="card-panel">
				<div id="total-clicks-chart"></div>
			</div>
		</div>
	</div>
}
<div class="row">
	<div class="col s6">
		<div class="card-panel">
			<div id="platforms-chart"></div>
		</div>
	</div>

	<div class="col s6">
		<div class="card-panel">
			<div id="browsers-chart"></div>
		</div>
	</div>
</div>

<script>
	google.charts.load('current', {packages: ['corechart']});
	google.charts.setOnLoadCallback(drawCharts);
	function drawTotalClicksChart() {
	  var data = google.visualization.arrayToDataTable([
		['day', 'clicks'],
	  ].concat(@Json.Serialize(Model.DailyClicks.Select(e => new object[] { e.Key, e.Value }))));
	  var options = {
		title: 'total clicks',
		haxis: {
		  title: 'day of month'
		},
		vaxis: {
		  title: 'clicks'
		}
	  };
	  var chart = new google.visualization.AreaChart(
		document.getElementById('total-clicks-chart')
	  );
	  chart.draw(data, options);
	}
	function drawBrowsersChart() {
	  var data = google.visualization.arrayToDataTable([
		['browser', 'clicks'],
	  ].concat(@Json.Serialize(Model.BrowseClicks.Select(e => new object[] { e.Key, e.Value }))));
	  var options = {
		title: 'Browsers'
	  };
	  var chart = new google.visualization.PieChart(
		document.getElementById('browsers-chart')
	  );
	  chart.draw(data, options);
	}
	function drawPlatformsChart() {
	  var data = google.visualization.arrayToDataTable([
		['platform', 'clicks'],
	  ].concat(@Json.Serialize(Model.PlatformClicks.Select(e => new object[] { e.Key, e.Value }))));
	  var options = {
		title: 'Platform'
	  };
	  var chart = new google.visualization.PieChart(
		document.getElementById('platforms-chart')
	  );
	  chart.draw(data, options);
	}
	function drawCharts() {
	  drawTotalClicksChart();
	  drawBrowsersChart();
	  drawPlatformsChart();
	}
</script>